version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    time: "12:00"
    timezone: "Europe/Zurich"
    day: "sunday"
- package-ecosystem: nuget
  directory: "/Backend"
  schedule:
    interval: weekly
    time: "12:00"
    timezone: "Europe/Zurich"
    day: "sunday"
- package-ecosystem: npm
  directory: "/Frontend"
  schedule:
    interval: weekly
    time: "12:00"
    timezone: "Europe/Zurich"
    day: "sunday"
  versioning-strategy: increase
