name: Frontend

on:
  push:
    branches:
      - master
      - stable
    paths:
      - Backend/**
      - .github/workflows/dotnetcore.yml
  pull_request:
    paths:
      - Frontend/**
      - .github/workflows/angular.yml

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    env:
      working-directory: ./Frontend

    steps:
    - uses: actions/checkout@v2
    - name: Use latest Node.js 14
      uses: actions/setup-node@v2.1.1
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: npm ci
      working-directory: ${{env.working-directory}}
    - name: Lint
      run: npm run lint
      working-directory: ${{env.working-directory}}
    - name: Build
      run: npm run ci:build
      working-directory: ${{env.working-directory}}
    - name: Test
      run: npm run ci:test
      working-directory: ${{env.working-directory}}
    - name: E2E
      run: npm run ci:e2e
      working-directory: ${{env.working-directory}}