name: Deployment

on:
  push:
    branches:
      - master
      - stable

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.4.0
      with:
        dotnet-version: 3.1.101
    - name: Use latest Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Build frontend
      run: |
        npm ci
        npm run deploy
      working-directory: ./Frontend
    - name: Build backend
      run: dotnet build --configuration Release
      working-directory: ./Backend
    - name: Bundle backend
      run: dotnet publish -c Release -o bundle
      working-directory: ./Backend
    - name: Azure deploy dev
      uses: azure/webapps-deploy@v1
      if: github.ref == 'refs/heads/master'
      with:
        app-name: hey-im-in-dev
        publish-profile: ${{ secrets.AZURE_WEBAPP_DEV_PUBLISH_PROFILE }}
        package: ./Backend/bundle
    - name: Azure deploy prod
      uses: azure/webapps-deploy@v1
      if: github.ref == 'refs/heads/stable'
      with:
        app-name: hey-im-in
        publish-profile: ${{ secrets.AZURE_WEBAPP_PROD_PUBLISH_PROFILE }}
        package: ./Backend/bundle