name: Backend

on:
  push:
    branches:
      - master
      - stable
    paths:
      - Backend/**
      - .github/workflows/dotnetcore.yml
  pull_request:
    paths:
      - Backend/**
      - .github/workflows/dotnetcore.yml

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    env:
      working-directory: ./Backend

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.6.0
      with:
        dotnet-version: 3.1.x
    - name: Build with dotnet
      run: dotnet build --configuration Release
      working-directory: ${{env.working-directory}}
    - name: Test with dotnet
      run: dotnet test --configuration Release
      working-directory: ${{env.working-directory}}
